### ISSUE TITLE
Appetite and Tough as Nails incompatibility of some kind

### ISSUE THREAD

**Issue by NosferatuTwo** [CCr4ft3r/appetite#11]
When loading into/creating a World the game crashes

Used mods; Appetite-1.16.5-1.5.1.jar , ToughAsNails-1.16.5-4.1.0.9-universal.jar , and notenoughcrashes-4.1.4+1.16.5-forge.jar

Forge version 36.2.34

Log Link:
https://gist.github.com/NosferatuTwo/01a5b56b0a36455353ca098577b7e5b2#file-the-log-fr

Crash report link:
https://gist.github.com/NosferatuTwo/892e3dfbccc353170d7280c792f63b42

**Comment by CCr4ft3r** [comment]
Unfortunately, I can't do anything here. 

Minecraft crashess because in this version Tough As Nails overrides the whole tick function of Minecrafts FoodStats class.
A mod shouldn't override whole methods of Minecrafts or Forges source code but instead use injection points via mixins.

In my opinion this should to be fixed on the other side.
