### ISSUE TITLE
[Suggestion] hunger bar do not relate to the level

### ISSUE THREAD

**Issue by blood789** [CCr4ft3r/appetite#9]
version：appetite-1.19.2-1.5.1.jar
First, set as below:	
initialHungerbarMaximum = 3
raisingHungerbarAfter = 5

1. Join the game, use xp bottle, when I reach level 5, I get another drumstick amount. (√)
2. When I use command, /xp add @s 10000, my level has increase, but did not get  another drumstick amount. (×)
3. When I get more hunger through the experience bottle, for example, I am 30 at this time, and then consume experience through the enchanting table, my level drops, but the hunger  does not follow the decline. (×)

**Comment by blood789** [comment]
I hope to be able to change the hunger value to follow the level change at any time, the hunger will increase when the level rises, and when the level drops (for example enchanting or die), it can also decrease together.

For example, you can add more rule im toml
startinghunger : 3,
minhunger : 3,
maxhunger : 10,
setOnDeath: 3,


Thanks for your works.

**Comment by CCr4ft3r** [comment]
Regarding your listed expectations:

2. This is intentional. I only invoke the rise of the hunger bar on the PickupXp event. 

3. This is also intentional. The hunger leveling feature was intentend to make the early game more difficult. 
Always loosing a drumstrick when the players level drops, would be probably a bit confusing and 
dangerous at times. For example: If you set initialHungerbarMaximum to 8 and raisingHungerbarAfter to 3 you will have all 10 drumsticks at reaching level 6. If you level up to level 30 over time and then looses 3 levels by an enchantment for 10 times the player would have 0 drumsticks :D
However I still appreciate your thoughts and expectations on this case. I can add a config option so that dropping players level below the last recorded level minus raisingHungerbarAfter will make you loose one drumstick as gained before. 
If you would like this as an option I can add it in the next update.

**Comment by CCr4ft3r** [comment]
In response to your second comment:

- startinghunger should be identical to the already existing option: initialHungerbarMaximum
- minhunger shouldn't be necessary if you can agree with my suggested solution for 3.
- maxhunger: I already though about such a feature back then, but setting this to a higher value than 10 would be against the concept of Appetite (after a certain time hunger wouldn't be challenging anymore) and setting it to a smaller value than 10 (so that the player can't gain 10), would be probably too difficult for certain (end game) situations.
- setOnDeath: I like this idea. I will add it to the next update.

Correct me if I'm wrong about a made consideration.

**Comment by blood789** [comment]
Thank you very much for the author's restoration. I basically agree with your modification suggestions.
Have you ever played a version called MITE? Based on the 1.6.4 magic modification, I really like the hunger system in it, and your MOD is the closest.

**Comment by blood789** [comment]
Also, when will it be updated to 1.20.1? 1.20.1，please！

**Comment by CCr4ft3r** [comment]
Glad you like Appetite :) I didn't know MITE before, but I agree that it seems similar in some ways.
I will update Appetite hopefully in this month (but certainly by January).
